# WEEK 7: Notes

In this week, we start by looking at the implementation of KNN in SK-Learn followed by SVM implementation.


# Nearest Neighbor Classifier

- It is a type of <span style="color:purple">instance-based</span> learning or <span style="color:purple">non-generalizing</span> learning
    - Does not attempt to **construct a model**
    - Simply stores instances of the training data
- Classification is computed from a simple <span style="color:purple">majority vote of the nearest neighbors</span> of each point.
- Two different implementations of nearest neighbors classifiers are available:
    1. ```KNeighboursClassifier```
    1. ```RadiusNeighborsClassifier```
    

## Difference between ```KNeighborsClassifier``` and ```RadiusNeighborsClassifier```

KNeighborsClassifier | RadiusNeighborsClassifier
--- | ---
Learning based on the k-nearest neighbors | Learning based on the number of neighbours within a fixed radius $r$ of each training point
Most commonly used technique | Used in cases where the data is not uniformly sampled
Choice of the value $K$ is highly data-dependent | Fixed value of $r$ is specified, such that points in sparser neighborhoods use fewer nearest neighbors for the classification

# KNeighborsClassifier

In [2]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_neighbors=4) # Default = 5

# TRAINING THE MODEL
# knn_clf.fit(X_train, y_train)


## Assigning weights to neighborhood in KNN
- It's better to weight the neighbors such that nearer neighbors contribute more to the fit
- the ```weight``` parameter can take 2 values:
    1. 'uniform': all points in each neighborhood are equallt weighted
    1. 'distance': weight points by the inverse of their distance. Closer neighbors of a query point will have a greater influence than neighbors which are further away

> Default weight = 'uniform'

## Defining our own weight values for KNN
- It is possible to define our own weights if we have an array of distances
- **```weights```** parameter also accepts a user-defined function which takes an array of distances as input and returns an array of the same shape containing the weights

In [3]:
def user_Weights(wt_array):
    return 2**wt_array

In [6]:
import numpy as np
user_Weights(np.asarray([1,2,3]))

array([2, 4, 8])

In [7]:
knn_clf = KNeighborsClassifier(weights=user_Weights)

## Algorithm used to compute the nearest neighbors

- **```algorithm```** parameter can take the following values:
    1. 'ball_tree': uses BallTree
    1. 'kd_tree': uses KDTree
    1. 'brute': uses brute-force search
    1. 'auto': will attempt to defice the most appropriate algorithm based on the values passed to the fit

> default algorithm = 'auto'

In [8]:
knn_clf = KNeighborsClassifier(algorithm="ball_tree")

## Additional Parameters for <span style="color:green">tree algorithm</span> in KNN

- For **"ball_tree"** and **"kd_tree"**, there are some other parameters to be set

1. ```leaf_size```
    - Can affect the speed of the construction and query, as well as the memory required to store the tree
    - default = 30

<br>

2. ```metric```
    - Distance metric to use for the tree
    - It is either string or a callable function
    - Some metrics are:
        - "euclidean"
        - "manhattan"
        - "chebyshev"
        - "minkowski"
        - "wminkowski"
        - "seuclidean"
        - "mahalanobis"
    - Default = 'minkowski'

<br>

3. ```p```
    - Power parameter for the Minkowski metric
    - Default = 2

# RadiusNeighborsClassifier

In [11]:
from sklearn.neighbors import RadiusNeighborsClassifier

rn_clf = RadiusNeighborsClassifier()

## Parameters for specifying the Radius
**```radius```**
- Number of neighbors is specified within a fixed radius $r$ of each training point, under this parameter
- Default = 1.0
- Takes float value

In [12]:
rn_clf = RadiusNeighborsClassifier(radius=1.5)

**```weights```**
- uniform
- distance [default]
- function [callable]

**```algorithm```**
- ball_tree
- kd_tree
- brute
- auto [default]

**```leaf_size```**
- 30 [default]

**```metric```**
- minkowski [default]
- All previously discussed metrics work here as well

**```p```**
- 2 [default]


In [13]:
rn_clf = RadiusNeighborsClassifier(radius=1.5,
                                   algorithm='ball_tree',
                                   leaf_size=27,
                                   metric='euclidean',
                                   p=2.4
                                  )

# Support Vector Machines

- 3 implementations of SVM in SK-Learn
    - SVC
    - NuSVC
    - LinearSVC

- ```SVC``` and ```NuSVC``` are very similar methods but accept slightly different sets of parameters.
    - Implementation is based on libsvm
- ```LinearSVC``` is a faster implementation of linear SVM classification with only <span style="color:purple">linear kernel</span>

# Implementing SVC

In [15]:
from sklearn.svm import SVC

svm_clf = SVC()

## <span style="color:Purple">Regularization</span> in SVC

**C** parameter is a regularizer in SVM.

$$
c \propto \dfrac{1}{width}
$$

- Strength of the regularization is inversely proportional to $C$
- Strictly positive
- Penalty is a squared l2 penalty

## ```Kernel``` parameter in SVM

- Can take the following values:
    1. <span style="color:green">'linear'</span>
    1. <span style="color:green">'poly'</span>
    1. <span style="color:green">'rbf'</span>
    1. <span style="color:green">'sigmoid'</span>
    1. <span style="color:green">'precomputed'</span>
- default kernel = 'rbf'
- Radial Basis Function
***
- If ```kernel = 'poly'```, set ```degree``` (any int value)

- ```gamma``` is the Kernel coefficient for 'rbf', 'poly' and 'sigmoid'
- RBF kernel function is given by:
$$
\kappa(\mathbf{u},\mathbf{v}) = \exp(-\gamma \|\mathbf{u}-\mathbf{v}\|^2)
$$

- Can take the following values:
    - 'scale'
$$
\text{value of gamma} = \dfrac{1}{\text{no. of features}\times X.Var()} 
$$

    - 'auto'
$$
\text{value of gamma} = \dfrac{1}{\text{no. of features}}
$$

    - float value




In [17]:
svm_clf = SVC(kernel='rbf', gamma='scale')

- If kernel = 'poly' or 'sigmoid', set ```coef0``` which is an independent term in kernel function (any int value)


## Viewing the support vectors
- After training, we can see the support vectors
- Support vectors are data points which lie on the margins

```python
svm_clf = SVC()
svm_clf.fit(X_train, y_train)

# to view indices of the support vectors
clf.support_

# To view the support vectors
clf.support_vectors_

# To view the number of support vectors for each class
clf.n_support_
```

In [18]:
from sklearn.datasets import load_breast_cancer

X, y = load_breast_cancer(return_X_y=True)

In [20]:
from sklearn.svm import SVC

svm_clf = SVC()
svm_clf.fit(X, y)


SVC()

In [21]:
# To view the support vector indices
svm_clf.support_

array([  3,   5,   7,   8,   9,  13,  14,  15,  22,  26,  31,  36,  38,
        39,  40,  41,  43,  44,  47,  54,  57,  62,  64,  65,  73,  86,
        91,  94,  99, 100, 105, 126, 135, 138, 146, 171, 177, 180, 184,
       190, 193, 194, 196, 199, 205, 212, 213, 214, 215, 223, 229, 255,
       257, 259, 263, 283, 297, 329, 330, 351, 353, 379, 385, 414, 430,
       435, 461, 479, 489, 501, 509, 512, 514, 536, 562,  19,  49,  89,
        90,  92,  93, 123, 125, 128, 133, 147, 148, 149, 157, 165, 169,
       204, 209, 220, 224, 225, 227, 235, 238, 243, 278, 290, 291, 298,
       311, 326, 340, 347, 363, 371, 375, 387, 406, 413, 421, 423, 434,
       437, 438, 442, 447, 448, 453, 455, 462, 465, 466, 472, 476, 477,
       481, 484, 486, 491, 495, 500, 508, 511, 513, 518, 523, 526, 532,
       541, 542, 545, 558, 560], dtype=int32)

In [22]:
# To view the support vectors
svm_clf.support_vectors_

array([[1.142e+01, 2.038e+01, 7.758e+01, ..., 2.575e-01, 6.638e-01,
        1.730e-01],
       [1.245e+01, 1.570e+01, 8.257e+01, ..., 1.741e-01, 3.985e-01,
        1.244e-01],
       [1.371e+01, 2.083e+01, 9.020e+01, ..., 1.556e-01, 3.196e-01,
        1.151e-01],
       ...,
       [1.362e+01, 2.323e+01, 8.719e+01, ..., 7.174e-02, 2.642e-01,
        6.953e-02],
       [1.459e+01, 2.268e+01, 9.639e+01, ..., 1.105e-01, 2.258e-01,
        8.004e-02],
       [1.405e+01, 2.715e+01, 9.138e+01, ..., 1.048e-01, 2.250e-01,
        8.321e-02]])

In [23]:
# To view the number of support vectors, for each class
svm_clf.n_support_

array([75, 73], dtype=int32)

In [28]:
# Number of features seen during fit
svm_clf.n_features_in_

30

In [30]:
X.shape

(569, 30)

In [31]:
svm_clf.score(X, y)

0.9226713532513181

# Implementing NuSVC ($\nu$-Support Vector Classifier)

- Similar to SVC but uses a new factor $\nu$ to control the number of support vectors 
- $\nu$ is used to set an upper-bound to the fraction of margin errors


In [32]:
from sklearn.svm import NuSVC

nu_svm = NuSVC()

## Significance of $\nu$ in NuSVC
- Instead of $C$, we have $\nu$ which is used to control the number of support vectors and margin errors
- $\nu$ is an upper-bound on the **fraction of margin errors** and a lower-bound of the **fraction of support vectors**

- $\nu \in (0,1]$
- Default $\nu = \textbf{0.5}$

- Other parameters are the same

# Implementing LinearSVC

In [33]:
from sklearn.svm import LinearSVC

linear_svm = LinearSVC()

## Advantages of LinearSVC
- It has more flexibility in the <span style="color:purple">choice of penalties and loss function</span> since it is implemented in terms of liblinear
- Scaled better to <span style="color:purple">large number of samples</span>
- SUpports both, dense and sparse input

## ```penalty``` in LinearSVC
- It can take 2 values:
    1. <span style="color:purple">$l1$</span>
    2. <span style="color:purple">$l2$</span>
    
- <span style="color:purple">$l1$</span> leads to coef_ vectors that are sparse

- Default penalty = **l2**

In [34]:
linear_svm = LinearSVC(penalty='l1')

## ```loss``` in LinearSVC

- The ```loss``` parameter can take 2 values:
    1. <span style="color:purple">'hinge'</span>: Standard SVM loss
    1. <span style="color:purple">'squared_hinge'</span>: Squared of the hinge loss

- Default loss = **squared_loss**

- **<span style="color:RED">NOTE THAT, the following combination is not allowed:</span>**
    - ```penalty='l1'``` and ```loss='hinge'```

***

# Some other parameters in LinearSVC

<span style="color:purple">$C$</span>
- Regularization parameter

<span style="color:purple">$dual$</span>
- Select the algorithm to either solve the dual or the primal optimization problem
- When ```n_samples```$>$```n_features```, prefer **<span style="color:red">dual = False</span>**

<span style="color:purple">$fit\_intercept$</span>
- To calculate the intercept for the model

In [35]:
linear_svm = LinearSVC(C=1.5,
                       dual=False, # Default = True
                       fit_intercept=True # Default = True
                      )

## Multi-Class Classification in SVM

- <span style="color:purple">SVC</span> and <span style="color:purple">NuSVC</span> implements **<span style="color:red">One-vs-One</span>** approach
- <span style="color:purple">LinearSVC</span> implements **<span style="color:red">One-vs-Rest</span>** approach

In [37]:
linear_svm.multi_class

'ovr'

## Advantages of SVM
- Effictive in high-dimensional spaces
- Effictive in cases where the number of dimensions is greater than the number of samples(n_features>n_samples)
- Uses a subset of training points in the decision function(called support vectors). Hence, it's memory efficient
- Versatile: Different kernel functions can be specifiedfor the decision function

## Disadvantages of SVM
- SVMs do not provide probability estimates directly. These are calculated using an expensive 5-fold CV
- Avoid over-fitting in choosing the kernel function if the number of features is much greater than the number of samples

